sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  on:
    branch: master
node_js:
  - node
  - '7'
  - '6'
script:
  - yarn build:lib
  - yarn build:dist
after_success:
  - yarn semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
